version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestbancaire_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    ports:
      - "8000:9000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: gestbancaire_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gestbancaire
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: oumy
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
